# ETL - Student Performance

## Extract

In [ ]:
import pandas as pd

from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("Gaming_Academic_Performance.csv")

In [3]:
df

,student_id,age,gender,gaming_hours,study_hours,sleep_hours,attendance,gaming_genre,social_activity,device_usage,reaction_time_ms,addiction_score,stress_level,grades
0,1,22,Male,7.23,8.78,6.96,91.44,FPS,3.25,9.36,235.84,14.69,Low,86.459555
1,2,19,Male,0.07,8.72,7.63,63.63,Casual,1.02,3.21,328.71,2.47,Medium,98.230000
2,3,23,Female,1.73,9.56,4.40,83.26,Casual,3.46,5.56,313.61,4.73,High,90.560000
3,4,20,Female,6.62,1.68,7.83,75.04,RPG,1.46,11.78,241.84,14.54,Low,32.670000
4,5,22,Female,5.36,5.83,5.55,65.57,FPS,1.01,8.23,249.31,12.48,Low,58.710000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,7996,24,Male,6.33,5.09,4.83,63.74,FPS,4.11,9.96,231.33,11.14,Low,35.110000
7996,7997,22,Female,5.77,6.09,6.23,84.37,FPS,3.42,11.19,254.13,10.66,Low,60.800000
7997,7998,20,Male,2.87,8.51,8.62,67.30,FPS,2.36,6.40,305.00,6.42,Medium,90.280000
7998,7999,22,Female,0.98,2.99,7.29,61.13,FPS,2.02,4.57,325.36,2.14,Medium,56.330000
7999,8000,18,Female,1.73,8.75,7.65,78.68,RPG,4.03,6.33,302.25,4.05,Medium,100.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   student_id        8000 non-null   int64
 1   age               8000 non-null   int64
 2   gender            8000 non-null   object
 3   gaming_hours      8000 non-null   float64
 4   study_hours       8000 non-null   float64
 5   sleep_hours       8000 non-null   float64
 6   attendance        8000 non-null   float64
 7   gaming_genre      8000 non-null   object
 8   social_activity   8000 non-null   float64
 9   device_usage      8000 non-null   float64
 10  reaction_time_ms  8000 non-null   float64
 11  addiction_score   8000 non-null   float64
 12  stress_level      8000 non-null   object
 13  grades            8000 non-null   float64
dtypes: float64(9), int64(2), object(3)
memory usage: 875.1+ KB

In [5]:
df.describe()

,student_id,age,gaming_hours,study_hours,sleep_hours,attendance,social_activity,device_usage,reaction_time_ms,addiction_score,grades
count,8000.00000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,4000.50000,19.983625,4.076562,5.448730,6.482910,79.886525,2.507790,7.586315,271.105839,9.908492,66.180776
std,2309.54541,2.587072,2.297137,2.559515,1.431871,11.580419,1.441128,2.710035,29.440675,5.035837,22.422024
min,1.00000,16.000000,0.000000,1.000000,4.000000,60.000000,0.000000,1.100000,183.260000,-4.510000,0.000000
25%,2000.75000,18.000000,2.130000,3.240000,5.240000,69.780000,1.287500,5.560000,247.160000,5.920000,49.879843
50%,4000.50000,20.000000,4.130000,5.460000,6.500000,79.695000,2.500000,7.610000,270.475000,10.005000,67.070000
75%,6000.25000,22.000000,6.040000,7.640000,7.690000,90.100000,3.760000,9.600000,294.690000,13.860000,83.992223
max,8000.00000,24.000000,8.000000,10.000000,9.000000,100.000000,5.000000,13.950000,347.870000,23.160000,118.632936

## Transform

In [6]:
df.isna().sum()

student_id          0
age                 0
gender              0
gaming_hours        0
study_hours         0
sleep_hours         0
attendance          0
gaming_genre        0
social_activity     0
device_usage        0
reaction_time_ms    0
addiction_score     0
stress_level        0
grades              0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
le = LabelEncoder()

df["gender"] = le.fit_transform(df["gender"])

stress_map = {
    "Low":0,
    "Medium":1,
    "High":2
}

df["stress_level"] = df["stress_level"].map(stress_map)

In [9]:
df

,student_id,age,gender,gaming_hours,study_hours,sleep_hours,attendance,gaming_genre,social_activity,device_usage,reaction_time_ms,addiction_score,stress_level,grades
0,1,22,1,7.23,8.78,6.96,91.44,FPS,3.25,9.36,235.84,14.69,0,86.459555
1,2,19,1,0.07,8.72,7.63,63.63,Casual,1.02,3.21,328.71,2.47,1,98.230000
2,3,23,0,1.73,9.56,4.40,83.26,Casual,3.46,5.56,313.61,4.73,2,90.560000
3,4,20,0,6.62,1.68,7.83,75.04,RPG,1.46,11.78,241.84,14.54,0,32.670000
4,5,22,0,5.36,5.83,5.55,65.57,FPS,1.01,8.23,249.31,12.48,0,58.710000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,7996,24,1,6.33,5.09,4.83,63.74,FPS,4.11,9.96,231.33,11.14,0,35.110000
7996,7997,22,0,5.77,6.09,6.23,84.37,FPS,3.42,11.19,254.13,10.66,0,60.800000
7997,7998,20,1,2.87,8.51,8.62,67.30,FPS,2.36,6.40,305.00,6.42,1,90.280000
7998,7999,22,0,0.98,2.99,7.29,61.13,FPS,2.02,4.57,325.36,2.14,1,56.330000
7999,8000,18,0,1.73,8.75,7.65,78.68,RPG,4.03,6.33,302.25,4.05,1,100.000000

## Load

In [10]:
df.to_csv("Gaming_Academic_Performance_ETL.csv", index=False)

## Data untuk Data Warehouse & Machine Learning

In [11]:
df_dw = df.copy()
df_ml = df.copy()

## Data Warehouse

In [12]:
df_dw["gender_id"] = df_dw["gender"]

In [13]:
genre_map = {
    "Casual":1,
    "FPS":2,
    "RPG":3
}

df_dw["genre_id"] = df_dw["gaming_genre"].map(genre_map)

In [14]:
df_dw["stress_id"] = df_dw["stress_level"]

In [15]:
df_dw = df_dw.drop(columns=["gender", "gaming_genre", "stress_level"])

In [16]:
df_dw = df_dw[
    [
        "student_id",
        "gender_id",
        "genre_id",
        "stress_id",
        "age",
        "gaming_hours",
        "study_hours",
        "sleep_hours",
        "attendance",
        "social_activity",
        "device_usage",
        "reaction_time_ms",
        "addiction_score",
        "grades"
    ]
]

In [17]:
df_dw

,student_id,gender_id,genre_id,stress_id,age,gaming_hours,study_hours,sleep_hours,attendance,social_activity,device_usage,reaction_time_ms,addiction_score,grades
0,1,1,2,0,22,7.23,8.78,6.96,91.44,3.25,9.36,235.84,14.69,86.459555
1,2,1,1,1,19,0.07,8.72,7.63,63.63,1.02,3.21,328.71,2.47,98.230000
2,3,0,1,2,23,1.73,9.56,4.40,83.26,3.46,5.56,313.61,4.73,90.560000
3,4,0,3,0,20,6.62,1.68,7.83,75.04,1.46,11.78,241.84,14.54,32.670000
4,5,0,2,0,22,5.36,5.83,5.55,65.57,1.01,8.23,249.31,12.48,58.710000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,7996,1,2,0,24,6.33,5.09,4.83,63.74,4.11,9.96,231.33,11.14,35.110000
7996,7997,0,2,0,22,5.77,6.09,6.23,84.37,3.42,11.19,254.13,10.66,60.800000
7997,7998,1,2,1,20,2.87,8.51,8.62,67.30,2.36,6.40,305.00,6.42,90.280000
7998,7999,0,2,1,22,0.98,2.99,7.29,61.13,2.02,4.57,325.36,2.14,56.330000
7999,8000,0,3,1,18,1.73,8.75,7.65,78.68,4.03,6.33,302.25,4.05,100.000000

In [18]:
df_dw.to_csv("Gaming_Academic_Performance_DW.csv", index=False)

## Data Machine Learning

In [20]:
df_ml = pd.get_dummies(
    df_ml,
    columns=["gaming_genre"],
    drop_first=False
)

In [21]:
df_ml.drop(columns=["student_id"], inplace=True)

In [22]:
df_ml

,age,gender,gaming_hours,study_hours,sleep_hours,attendance,social_activity,device_usage,reaction_time_ms,addiction_score,stress_level,grades,gaming_genre_Casual,gaming_genre_FPS,gaming_genre_RPG
0,22,1,7.23,8.78,6.96,91.44,3.25,9.36,235.84,14.69,0,86.459555,False,True,False
1,19,1,0.07,8.72,7.63,63.63,1.02,3.21,328.71,2.47,1,98.230000,True,False,False
2,23,0,1.73,9.56,4.40,83.26,3.46,5.56,313.61,4.73,2,90.560000,True,False,False
3,20,0,6.62,1.68,7.83,75.04,1.46,11.78,241.84,14.54,0,32.670000,False,False,True
4,22,0,5.36,5.83,5.55,65.57,1.01,8.23,249.31,12.48,0,58.710000,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,24,1,6.33,5.09,4.83,63.74,4.11,9.96,231.33,11.14,0,35.110000,False,True,False
7996,22,0,5.77,6.09,6.23,84.37,3.42,11.19,254.13,10.66,0,60.800000,False,True,False
7997,20,1,2.87,8.51,8.62,67.30,2.36,6.40,305.00,6.42,1,90.280000,False,True,False
7998,22,0,0.98,2.99,7.29,61.13,2.02,4.57,325.36,2.14,1,56.330000,False,True,False
7999,18,0,1.73,8.75,7.65,78.68,4.03,6.33,302.25,4.05,1,100.000000,False,False,True

In [ ]:
df_ml.to_csv("Gaming_Academic_Performance_DM.csv", index=False)